import { IMAGES } from "../assets/Images";
import { Trans } from "../translation";
import { COLORS } from "./theme";

export const DUMMY_DATA = {
  NATIONALITY: [
    {
      id: 1,
      name: 'مصري',
      nameEn: 'Egypt',
    },
    {
      id: 2,
      name: 'سعودي',
      nameEn: 'Saudi',
    },
  ],
  POSITIONS: [
    {
      id: 1,
      name: 'موظف',
      nameEn: 'Employee',
    },
  ],
  DAYS: [
    {
      id: 1,
      name: 'السبت',
      nameEn: 'saturday',
    },
    {
      id: 2,
      name: 'الاحد',
      nameEn: 'sunday',
    },
    {
      id: 3,
      name: 'الاثنين',
      nameEn: 'monday',
    },
    {
      id: 4,
      name: 'الثلاثاء',
      nameEn: 'tuesday',
    },
    {
      id: 5,
      name: 'الاربعاء',
      nameEn: 'wednesday',
    },
    {
      id: 6,
      name: 'الخميس',
      nameEn: 'thursday',
    },
    {
      id: 7,
      name: 'الجمعة',
      nameEn: 'friday',
    },
  ],
  TIMING: [
    {
      id: 1,
      name: 'سنوي',
      nameEn: 'Yearly',
      key: 'isYear',
    },
    {
      id: 2,
      name: 'شهري',
      nameEn: 'Monthly',
      key: 'isMonth',
    },
    {
      id: 3,
      name: 'اسبوعي',
      nameEn: 'Weekly',
      key: 'isWeek',
    },
  ],
  YEARS: [
    {
      id: 0,
      name: '2020',
      nameEn: '2020',
      date: '2020-01-01T09:00:00.000Z',
    },
    {
      id: 1,
      name: '2021',
      nameEn: '2021',
      date: '2021-01-01T09:00:00.000Z',
    },
    {
      id: 2,
      name: '2022',
      nameEn: '2022',
      date: '2022-01-01T09:00:00.000Z',
    },
    {
      id: 3,
      name: '2023',
      nameEn: '2023',
      date: '2023-01-01T09:00:00.000Z',
    },
    {
      id: 4,
      name: '2024',
      nameEn: '2024',
      date: '2024-01-01T09:00:00.000Z',
    },
    {
      id: 5,
      name: '2025',
      nameEn: '2025',
      date: '2025-01-01T09:00:00.000Z',
    },

  ],
  CHART1: [
    {value: 80, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 26, label: Trans('saturday')},
    {value: 30, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 70, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 26, label: Trans('sunday')},
    {value: 40, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 95, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 26, label: Trans('monday')},
    {value: 20, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 82, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 26, label: Trans('tuesday')},
    {value: 49, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 60, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 26, label: Trans('wednesday')},
    {value: 38, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 87, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 26, label: Trans('thursday')},
    {value: 29, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 77, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 26, label: Trans('friday')},
    {value: 38, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},
  ],
  CHART2_DATA1: [
    {value: 630, label: Trans('saturday'), showXAxisIndex: true},
    {value: 330, label: Trans('sunday'), showXAxisIndex: true},
    {value: 800, label: Trans('monday'), showXAxisIndex: true},
    {value: 350, label: Trans('tuesday'), showXAxisIndex: true},
    {value: 200, label: Trans('wednesday'), showXAxisIndex: true},
    {value: 790, label: Trans('thursday'), showXAxisIndex: true},
    {value: 280, label: Trans('friday'), showXAxisIndex: true},
  ],
  CHART2_DATA2: [
    {value: 550, label: Trans('saturday'), showXAxisIndex: true},
    {value: 450, label: Trans('sunday'), showXAxisIndex: true},
    {value: 250, label: Trans('monday'), showXAxisIndex: true},
    {value: 470, label: Trans('tuesday'), showXAxisIndex: true},
    {value: 930, label: Trans('wednesday'), showXAxisIndex: true},
    {value: 470, label: Trans('thursday'), showXAxisIndex: true},
    {value: 350, label: Trans('friday'), showXAxisIndex: true},
  ],
  NOTIFICATIONS: [
    { title: 'طلب جديد' },
    { title: 'قبول عرض' },
    { title: 'رفض عرض' },
    { title: 'اقتراب موعد حجز' },
  ],
  BLOCKAPPOINTMENTS: [
    {
      id: 1,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      timeFrom: '15:00:00',
      timeTo: '15:00:00',
      type: 'محجوز',
    },
    {
      id: 2,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      type: 'مغلق لفترة',
    },
    {
      id: 3,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      timeFrom: '15:00:00',
      timeTo: '15:00:00',
      type: 'محجوز',
    },
    {
      id: 4,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      type: 'مغلق لفترة',
    },
    {
      id: 5,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      timeFrom: '15:00:00',
      timeTo: '15:00:00',
      type: 'محجوز',
    },
  ],

  SERVICES: [
    {
      id: 123,
      image: IMAGES.serviceTest,
      nameAr: 'دخمة ١',
      nameEn: 'service 1',
      price: '100',
      category: 'تقليم اظافر',
      time: '30',
      state: 'pending',
      myStateId: 1,
    },
    {
      id: 234,
      image: IMAGES.serviceTest,
      nameAr: 'دخمة ٢',
      nameEn: 'service 2',
      price: '120',
      category: 'تقليم اظافر',
      time: '35',
      state: 'reviewing',
      myStateId: 2,
    },
    {
      id: 345,
      image: IMAGES.serviceTest,
      nameAr: 'دخمة ٣',
      nameEn: 'service 3',
      price: '70',
      category: 'تقليم اظافر',
      time: '20',
      state: 'approved',
      myStateId: 1,
    },
    {
      id: 456,
      image: IMAGES.serviceTest,
      nameAr: 'دخمة ٤',
      nameEn: 'service 4',
      price: '150',
      category: 'تقليم اظافر',
      time: '40',
      state: 'rejected',
      myStateId: 2,
    },

  ],
  SERVICESTATUES: [
    {
      id: 1,
      name: 'مفعلة',
      nameEn: 'active',
    },
    {
      id: 2,
      name: 'غير مفعلة',
      nameEn: 'deactivated',
    }
  ],
  EMPLOYEES: [
    {
      id: 123,
      name: 'شروق',
      saloneNameAr: 'صالون ١',
      saloneNameEn: 'Salon 1',
      branchNameAr: 'فرع ١',
      branchNameEn: 'Branch 1',
      email: 'shrouk@gmail.com',
      phoneNumber: '+966540802488',
      stateId: 1,
    },
    {
      id: 234,
      name: 'وجدان',
      saloneNameAr: 'صالون ١',
      saloneNameEn: 'Salon 1',
      branchNameAr: 'فرع ٢',
      branchNameEn: 'Branch 2',
      email: 'wgdan@gmail.com',
      phoneNumber: '+966540802488',
      stateId: 2,
    },
    {
      id: 345,
      name: 'سمر',
      saloneNameAr: 'صالون ١',
      saloneNameEn: 'Salon 1',
      branchNameAr: 'فرع ٢',
      branchNameEn: 'Branch 2',
      email: 'smar@gmail.com',
      phoneNumber: '+966540802488',
      stateId: 1,
    },
    {
      id: 456,
      name: 'ساره',
      saloneNameAr: 'صالون ١',
      saloneNameEn: 'Salon 1',
      branchNameAr: 'فرع ١',
      branchNameEn: 'Branch 1',
      email: 'sara@gmail.com',
      phoneNumber: '+966540802488',
      stateId: 2,
    },
  ],
  TIMINGS: [
    { id: 0, title: 'بداية اليوم', hour: 0, minute: 0 }, 
    { id: 1, title: '00:30', hour: 0, minute: 30 }, 
    { id: 2, title: '01:00', hour: 1, minute: 0 }, 
    { id: 3, title: '01:30', hour: 1, minute: 30 },
    { id: 4, title: '02:00', hour: 2, minute: 0 },
    { id: 5, title: '02:30', hour: 2, minute: 30 },
    { id: 6, title: '03:00', hour: 3, minute: 0 },
    { id: 7, title: '03:30', hour: 3, minute: 30 }, 
    { id: 8, title: '04:00', hour: 4, minute: 0 },
    { id: 9, title: '04:30', hour: 4, minute: 30 },
    { id: 10, title: '05:00', hour: 5, minute: 0 },
    { id: 11, title: '05:30', hour: 5, minute: 30 }, 
    { id: 12, title: '06:00', hour: 6, minute: 0 },
    { id: 13, title: '06:30', hour: 6, minute: 30 }, 
    { id: 14, title: '07:00', hour: 7, minute: 0 },
    { id: 15, title: '07:30', hour: 7, minute: 30 }, 
    { id: 16, title: '08:00', hour: 8, minute: 0 },
    { id: 17, title: '08:30', hour: 8, minute: 30 }, 
    { id: 18, title: '09:00', hour: 9, minute: 0 },
    { id: 19, title: '09:30', hour: 9, minute: 30 },
    { id: 20, title: '10:00', hour: 10, minute: 0 },
    { id: 21, title: '00:30', hour: 10, minute: 30 },
    { id: 22, title: '11:00', hour: 11, minute: 0 },
    { id: 23, title: '11:30', hour: 11, minute: 30 }, 
    { id: 24, title: '12:00', hour: 12, minute: 0 },
    { id: 25, title: '12:30', hour: 12, minute: 30 }, 
    { id: 26, title: '13:00', hour: 13, minute: 0 },
    { id: 27, title: '13:30', hour: 13, minute: 30 }, 
    { id: 28, title: '14:00', hour: 14, minute: 0 },
    { id: 29, title: '14:30', hour: 14, minute: 30 }, 
    { id: 30, title: '15:00', hour: 15, minute: 0 },
    { id: 31, title: '15:30', hour: 15, minute: 30 }, 
    { id: 32, title: '16:00', hour: 16, minute: 0 },
    { id: 33, title: '16:30', hour: 16, minute: 30 }, 
    { id: 34, title: '17:00', hour: 17, minute: 0 },
    { id: 35, title: '17:30', hour: 17, minute: 30 }, 
    { id: 36, title: '18:00', hour: 18, minute: 0 },
    { id: 37, title: '18:30', hour: 18, minute: 30 }, 
    { id: 38, title: '19:00', hour: 19, minute: 0 },
    { id: 39, title: '19:30', hour: 19, minute: 30 }, 
    { id: 40, title: '20:00', hour: 20, minute: 0 },
    { id: 41, title: '20:30', hour: 20, minute: 30 }, 
    { id: 42, title: '21:00', hour: 21, minute: 0 },
    { id: 43, title: '21:30', hour: 21, minute: 30 },
    { id: 44, title: '22:00', hour: 22, minute: 0 }, 
    { id: 45, title: '22:30', hour: 22, minute: 30 },
    { id: 46, title: '23:00', hour: 23, minute: 0 },
    { id: 47, title: '23:30', hour: 23, minute: 30 },
    { id: 48, title: 'نهاية اليوم', hour: 23, minute: 59 }, 
  ],
  CATEGORIES: [
    { id: 1, nameAr: 'العناية بالبشرة', nameEn: 'skin care' },
    { id: 2, nameAr: 'الاظافر', nameEn: 'nails' },
    { id: 3, nameAr: 'المكياج', nameEn: 'make-up' },
    { id: 4, nameAr: 'تسريح الشعر', nameEn: 'hear styling' },
    { id: 5, nameAr: 'التدليك', nameEn: 'massage' },
    { id: 6, nameAr: 'ثقب', nameEn: 'hole' },
    { id: 7, nameAr: 'مجموعة خدمات', nameEn: 'service group' },
  ],
  APPOINTMENT_STATUS: [
    {
      key: 'initiated',
      name: 'البداية',
      nameEn: 'initiated',
    },
    {
      key: 'pending_review_by_service_provider',
      name: 'في انتظار المراجعة بواسطة مقدم الخدمة',
      nameEn: 'pending review by service provider',
    },
    {
      key: 'reviewing',
      name: 'مراجعة',
      nameEn: 'reviewing',
    },
    {
      key: 'accepted_by_service_provider',
      name: 'مقبول بواسطة مقدم الخدمة',
      nameEn: 'accepted by service provider',
    },
    {
      key: 'rejected_by_service_provider',
      name: 'مرفوض بواسطة مقدم الخدمة',
      nameEn: 'rejected by service provider',
    },
    {
      key: 'confirmed_by_customer',
      name: 'تم تأكيده بواسطة العميل',
      nameEn: 'confirmed by customer',
    },
    {
      key: 'scheduled',
      name: 'تم الدفع',
      nameEn: 'scheduled',
    },
    {
      key: 'en_route',
      name: 'في الطريق',
      nameEn: 'in route',
    },
    {
      key: 'arrived',
      name: 'وصل',
      nameEn: 'arrived',
    },
    {
      key: 'started',
      name: 'بدأت',
      nameEn: 'started',
    },
    {
      key: 'completed',
      name: 'مكتمل',
      nameEn: 'completed',
    },
    {
      key: 'cancelled',
      name: 'ملغي',
      nameEn: 'cancelled',
    },
    {
      key: 'pending_payment',
      name: 'في انتظار الدفع',
      nameEn: 'pending payment',
    },
  ],
  APPOINTMENT: {
    id: 203,
    createdAt: "2024-07-24T09:54:36.556Z",
    updatedAt: "2024-07-24T10:04:18.682Z",
    status: "rejected_by_service_provider",
    cancelBy: null,
    type: "in_home",
    customerId: 18,
    serviceProviderId: 2,
    branchId: null,
    lat: "4.7248316",
    lng: "46.4928868",
    address: "المنزل",
    location: null,
    customerName: "ahmed ff",
    deletedAt: null,
    invoice: {
      id: 206,
      createdAt: "2024-07-24T09:54:36.556Z",
      updatedAt: "2024-07-24T09:54:36.556Z",
      amount: "128.57",
      totalOfferDiscount: "0.00",
      totalCouponDiscount: "0.00",
      totalPriceAfterDiscount: "128.57",
      discountAmount: "0.00",
      type: "appointment",
      walletId: null,
      appointmentId: 203,
      customerId: 18,
      serviceProviderId: null,
      currencyId: 1,
      status: "PENDING",
      commission: "15.00",
      deletedAt: null,
      couponId: null,
      eInvoiceId: null,
      eInvoiceUrl: null,
      eInvoiceName: null,
      payment: null
    },
    serviceProvider: {
      id: 2,
      createdAt: "2024-02-08T20:57:10.274Z",
      updatedAt: "2024-07-24T12:16:32.651Z",
      serviceProviderTypeId: 2,
      name: "mahmsoussd mahmoudsn",
      nameEn: "vbbbb",
      description: "bbbbn",
      descriptionEn: "bbbbbb",
      featuredImag: "1719214470056.2df98241-c2c0-45d1-bfb4-5bbad252d126.jpg",
      address: "bbbbbbb",
      addressEn: "bbbb",
      isActive: true,
      isFeatured: true,
      managerId: 3,
      countryId: 1,
      cityId: 1,
      commission: "15.00",
      homeServiceCost: "10.00",
      gapTim: 0,
      deletedAt: null,
    },
    branch: null,
    customer: {
      id: 18,
      createdAt: "2024-02-28T13:55:26.362Z",
      updatedAt: "2024-07-03T21:51:05.699Z",
      firstName: "aaaaaaaaaaaaaaaaaaaa",
      lastName: "ff",
      name: "ahmed ff",
      email: "mahmoud.arabella@gmail.com",
      resetPasswordCode: null,
      resetPasswordCodeExpireAt: null,
      phoneNumber: "+96652000000002",
      isActive: true,
      phoneNumberVerificationCode: null,
      verificationCodeExpireAt: null,
      isPhoneNumberVerified: false,
      role: "customer",
      deviceId: null,
      serviceProviderId: 17,
      cityId: null,
      points: 0,
      deletedAt: null,
      eInvoiceClientId: 6,
    },
    serviceBookings: [
      {
        id: 228,
        createdAt: "2024-07-24T09:54:36.556Z",
        updatedAt: "2024-07-24T09:54:36.556Z",
        status: "initiated",
        scheduledAt: "2024-07-24T12:00:00.000Z",
        bookingEndAt: "2024-07-24T13:00:00.000Z",
        serviceId: 2,
        employeeId: null,
        appointmentId: 203,
        couponId: null,
        offerId: null,
        priceWithVat: "128.57",
        offerDiscount: "0.00",
        couponDiscount: "0.00",
        priceAfterDiscount: "128.57",
        discountAmount: "0.00",
        vatRate: "15.0",
        service: {
          id: 2,
          createdAt: "2024-02-08T21:02:59.732Z",
          updatedAt: "2024-06-30T20:01:58.636Z",
          name: "خدمة11",
          nameEn: "خدمة11",
          description: "1خدمة1",
          descriptionEn: "خدمة11",
          featuredImage: "",
          price: "111.80",
          priceWithVat: "128.57",
          state: "approved",
          isActive: true,
          estimatedTime: 60,
          categoryId: 1,
          serviceProviderId: 2,
          taxId: 3,
          isTaxIncluded: false,
          deletedAt: null,
          isHomeService: true,
        }
      },
      {
        id: 228,
        createdAt: "2024-07-24T09:54:36.556Z",
        updatedAt: "2024-07-24T09:54:36.556Z",
        status: "initiated",
        scheduledAt: "2024-07-24T12:00:00.000Z",
        bookingEndAt: "2024-07-24T13:00:00.000Z",
        serviceId: 2,
        employeeId: null,
        appointmentId: 203,
        couponId: null,
        offerId: null,
        priceWithVat: "128.57",
        offerDiscount: "0.00",
        couponDiscount: "0.00",
        priceAfterDiscount: "128.57",
        discountAmount: "0.00",
        vatRate: "15.0",
        service: {
          id: 2,
          createdAt: "2024-02-08T21:02:59.732Z",
          updatedAt: "2024-06-30T20:01:58.636Z",
          name: "خدمة11",
          nameEn: "خدمة11",
          description: "1خدمة1",
          descriptionEn: "خدمة11",
          featuredImage: "",
          price: "111.80",
          priceWithVat: "128.57",
          state: "approved",
          isActive: true,
          estimatedTime: 60,
          categoryId: 1,
          serviceProviderId: 2,
          taxId: 3,
          isTaxIncluded: false,
          deletedAt: null,
          isHomeService: true,
        }
      },
      {
        id: 228,
        createdAt: "2024-07-24T09:54:36.556Z",
        updatedAt: "2024-07-24T09:54:36.556Z",
        status: "initiated",
        scheduledAt: "2024-07-24T12:00:00.000Z",
        bookingEndAt: "2024-07-24T13:00:00.000Z",
        serviceId: 2,
        employeeId: null,
        appointmentId: 203,
        couponId: null,
        offerId: null,
        priceWithVat: "128.57",
        offerDiscount: "0.00",
        couponDiscount: "0.00",
        priceAfterDiscount: "128.57",
        discountAmount: "0.00",
        vatRate: "15.0",
        service: {
          id: 2,
          createdAt: "2024-02-08T21:02:59.732Z",
          updatedAt: "2024-06-30T20:01:58.636Z",
          name: "خدمة11",
          nameEn: "خدمة11",
          description: "1خدمة1",
          descriptionEn: "خدمة11",
          featuredImage: "",
          price: "111.80",
          priceWithVat: "128.57",
          state: "approved",
          isActive: true,
          estimatedTime: 60,
          categoryId: 1,
          serviceProviderId: 2,
          taxId: 3,
          isTaxIncluded: false,
          deletedAt: null,
          isHomeService: true,
        }
      },
    ],
    appointmentFees: [],
  },
};