import { IMAGES } from "../assets/Images";
import { Trans } from "../translation";
import { COLORS } from "./theme";

export const DUMMY_DATA = {
  CHART1: [
    {value: 80, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 6, label: Trans('saturday')},
    {value: 30, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 70, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 6, label: Trans('sunday')},
    {value: 40, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 95, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 6, label: Trans('monday')},
    {value: 20, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 82, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 6, label: Trans('tuesday')},
    {value: 49, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 60, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 6, label: Trans('wednesday')},
    {value: 38, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 87, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 6, label: Trans('thursday')},
    {value: 29, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},

    {value: 77, frontColor: COLORS.secondGradient, gradientColor: COLORS.primaryGradient, spacing: 6, label: Trans('friday')},
    {value: 38, frontColor: COLORS.borderLight, gradientColor: COLORS.borderLight},
  ],
  CHART2_DATA1: [
    {value: 630, label: Trans('saturday'), showXAxisIndex: true},
    {value: 330, label: Trans('sunday'), showXAxisIndex: true},
    {value: 800, label: Trans('monday'), showXAxisIndex: true},
    {value: 350, label: Trans('tuesday'), showXAxisIndex: true},
    {value: 200, label: Trans('wednesday'), showXAxisIndex: true},
    {value: 790, label: Trans('thursday'), showXAxisIndex: true},
    {value: 280, label: Trans('friday'), showXAxisIndex: true},
  ],
  CHART2_DATA2: [
    {value: 550, label: Trans('saturday'), showXAxisIndex: true},
    {value: 450, label: Trans('sunday'), showXAxisIndex: true},
    {value: 250, label: Trans('monday'), showXAxisIndex: true},
    {value: 470, label: Trans('tuesday'), showXAxisIndex: true},
    {value: 930, label: Trans('wednesday'), showXAxisIndex: true},
    {value: 470, label: Trans('thursday'), showXAxisIndex: true},
    {value: 350, label: Trans('friday'), showXAxisIndex: true},
  ],
  NOTIFICATIONS: [
    { title: 'طلب جديد' },
    { title: 'قبول عرض' },
    { title: 'رفض عرض' },
    { title: 'اقتراب موعد حجز' },
  ],
  BLOCKAPPOINTMENTS: [
    {
      id: 1,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      timeFrom: '15:00:00',
      timeTo: '15:00:00',
      type: 'محجوز',
    },
    {
      id: 2,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      type: 'مغلق لفترة',
    },
    {
      id: 3,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      timeFrom: '15:00:00',
      timeTo: '15:00:00',
      type: 'محجوز',
    },
    {
      id: 4,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      type: 'مغلق لفترة',
    },
    {
      id: 5,
      title: '#1234',
      dateFron: 'Jun 3, 2024/06/2024',
      dateTo: 'Jun 3, 2024/06/2024',
      timeFrom: '15:00:00',
      timeTo: '15:00:00',
      type: 'محجوز',
    },
  ],

  SERVICES: [
    {
      id: 123,
      image: IMAGES.serviceTest,
      nameAr: 'دخمة ١',
      nameEn: 'service 1',
      price: '100',
      category: 'تقليم اظافر',
      time: '30',
      state: 'pending',
      myStateId: 1,
    },
    {
      id: 234,
      image: IMAGES.serviceTest,
      nameAr: 'دخمة ٢',
      nameEn: 'service 2',
      price: '120',
      category: 'تقليم اظافر',
      time: '35',
      state: 'reviewing',
      myStateId: 2,
    },
    {
      id: 345,
      image: IMAGES.serviceTest,
      nameAr: 'دخمة ٣',
      nameEn: 'service 3',
      price: '70',
      category: 'تقليم اظافر',
      time: '20',
      state: 'approved',
      myStateId: 1,
    },
    {
      id: 456,
      image: IMAGES.serviceTest,
      nameAr: 'دخمة ٤',
      nameEn: 'service 4',
      price: '150',
      category: 'تقليم اظافر',
      time: '40',
      state: 'rejected',
      myStateId: 2,
    },

  ],
  SERVICESTATUES: [
    { id: 1,
      nameAr: 'مفعلة',
      nameEn: 'active',
    },
    { id: 2,
      nameAr: 'غير مفعلة',
      nameEn: 'deactivated',
    }
  ],
  EMPLOYEES: [
    {
      id: 123,
      name: 'شروق',
      saloneNameAr: 'صالون ١',
      saloneNameEn: 'Salon 1',
      branchNameAr: 'فرع ١',
      branchNameEn: 'Branch 1',
      email: 'shrouk@gmail.com',
      phoneNumber: '+966540802488',
      stateId: 1,
    },
    {
      id: 234,
      name: 'وجدان',
      saloneNameAr: 'صالون ١',
      saloneNameEn: 'Salon 1',
      branchNameAr: 'فرع ٢',
      branchNameEn: 'Branch 2',
      email: 'wgdan@gmail.com',
      phoneNumber: '+966540802488',
      stateId: 2,
    },
    {
      id: 345,
      name: 'سمر',
      saloneNameAr: 'صالون ١',
      saloneNameEn: 'Salon 1',
      branchNameAr: 'فرع ٢',
      branchNameEn: 'Branch 2',
      email: 'smar@gmail.com',
      phoneNumber: '+966540802488',
      stateId: 1,
    },
    {
      id: 456,
      name: 'ساره',
      saloneNameAr: 'صالون ١',
      saloneNameEn: 'Salon 1',
      branchNameAr: 'فرع ١',
      branchNameEn: 'Branch 1',
      email: 'sara@gmail.com',
      phoneNumber: '+966540802488',
      stateId: 2,
    },
  ],
  TIMINGS: [
    { id: 0, title: 'بداية اليوم' },
    { id: 1, title: '00:30' },
    { id: 2, title: '01:00' },
    { id: 3, title: '01:30' },
    { id: 4, title: '02:00' },
    { id: 5, title: '02:30' },
    { id: 6, title: '03:00' },
    { id: 7, title: '03:30' },
    { id: 8, title: '04:00' },
    { id: 9, title: '04:30' },
    { id: 10, title: '05:00' },
    { id: 11, title: '05:30' },
    { id: 12, title: '06:00' },
    { id: 13, title: '06:30' },
    { id: 14, title: '07:00' },
    { id: 15, title: '07:30' },
    { id: 16, title: '08:00' },
    { id: 17, title: '08:30' },
    { id: 18, title: '09:00' },
    { id: 19, title: '09:30' },
    { id: 20, title: '10:00' },
    { id: 21, title: '00:30' },
    { id: 22, title: '11:00' },
    { id: 23, title: '11:30' },
    { id: 24, title: '12:00' },
    { id: 25, title: '12:30' },
    { id: 26, title: '13:00' },
    { id: 27, title: '13:30' },
    { id: 28, title: '14:00' },
    { id: 29, title: '14:30' },
    { id: 30, title: '15:00' },
    { id: 31, title: '15:30' },
    { id: 32, title: '16:00' },
    { id: 33, title: '16:30' },
    { id: 34, title: '17:00' },
    { id: 35, title: '17:30' },
    { id: 36, title: '18:00' },
    { id: 37, title: '18:30' },
    { id: 38, title: '19:00' },
    { id: 39, title: '19:30' },
    { id: 40, title: '20:00' },
    { id: 41, title: '20:30' },
    { id: 42, title: '21:00' },
    { id: 43, title: '21:30' },
    { id: 44, title: '22:00' },
    { id: 45, title: '22:30' },
    { id: 46, title: '33:00' },
    { id: 47, title: '33:30' },
    { id: 48, title: 'نهاية اليوم' },
  ],
  CATEGORIES: [
    { id: 1, nameAr: 'العناية بالبشرة', nameEn: 'skin care' },
    { id: 2, nameAr: 'الاظافر', nameEn: 'nails' },
    { id: 3, nameAr: 'المكياج', nameEn: 'make-up' },
    { id: 4, nameAr: 'تسريح الشعر', nameEn: 'hear styling' },
    { id: 5, nameAr: 'التدليك', nameEn: 'massage' },
    { id: 6, nameAr: 'ثقب', nameEn: 'hole' },
    { id: 7, nameAr: 'مجموعة خدمات', nameEn: 'service group' },
  ],
};