export default {
  baseUrl: 'https://onaddress.net/api/client/mobile/',
  topikAll: 'dev_user_all',
  topik: 'dev_user_',
  realtime: 'dev_',
  imageUrl: 'https://araberlla-staging.s3.me-south-1.amazonaws.com/',
  //=========================
  login: 'auth/login/pnp',
  forgot_password: '/auth/forgot-password',
  verifyOTP: 'auth/otp',
  reset_password: 'auth/reset-password',
  cities: 'admins/cities',


  uploadFile: 'admins/files/upload',
  categories: 'categories',
  brancheAction: 'admins/branches',
  serviceAction: 'admins/services',
  employeeAction: 'admins/employees',
  slotAction: 'admins/occupied-slots',
  appointments: 'admins/appointments',
  statistics: 'admins/statistics',
  service_providers: '/admins/service_providers',
  profiles: 'profiles',
  users: '/admins/users',
  notifications: 'admins/notifications',


  register: 'auth/register',
  confirm_code: 'auth/confirm',
  update_password: 'auth/update-password',
  user_data: 'auth/client-info',
  update_user_data: 'auth/update-data',
  upgraded_user_data: 'auth/update-company-details',
  types: 'properties/types',
  
  facilities: 'properties/facilities',
  features: 'properties/features',
  allCities: 'api/client/mobile/cities',
  areas: 'areas',
  sliders:'sliders',
  create_property: 'properties/create',
  edit_property: 'properties/edit',
  removeImages: 'properties/remove-image',
  uploadImage: 'properties/upload-image',
  allProperties: 'all-properties',
  properties: 'properties',
  requests: 'requests-properties',
  request_change_state: 'requests-properties/change-status',
  all_requests: 'public-all-properties-requests',
  agents: 'all-clients',
  settings: 'settings',
  reports_reasons: 'reports/reasons',
  create_report: 'reports/create',
  getfavouritesProperty: 'properties/favourites/list-properties',
  getfavouritesRequest: 'properties/favourites/list-properties-requests',
  createfavourites: 'properties/favourites/create',
  deletefavourites: 'properties/favourites/delete',
  plans: 'plans',
  myPlan: 'my-plan',
  buyPlan:'buy-plan',
  transactions: 'transactions-history',
  contactUs: 'contact-us',
  save_fcm_token: 'auth/save-fcm-token',
  all_notifications: 'auth/all-notifications',
  unread_notifications: 'auth/unread-notifications',
  make_notification_read: 'auth/make-notification-read',
};
